export const routes = {
    register: "/register",
    otp: "/otp",
    profile: "/profile",
    home: "/home",
    default: "/",
    login: "/login",
    notFound: "*",
    profileEvent: "/profile/event",
    profileBlog: "/profile/blog",
    destinations: "/destinations",
    createEvent: "/create/event",
    blog: "/blog",
    blogs: "/blogs/all",
    create: "/blog/create",
    gallery: "/gallery",
    guiderHire: "/guider/hire",
    contact: "/contact",
    adminLogin: "/admin/login",
};
