import "./globals.css";
import { Providers } from "./redux/Provider";
import UserRootLayout from "./userRootLayout";
export const metadata = {
    title: "Tourist Guide",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body suppressHydrationWarning={true}>
                <Providers>
                    <UserRootLayout>{children}</UserRootLayout>
                </Providers>
            </body>
        </html>
    );
}
