import { Providers } from "@/redux/Provider";
import "./globals.css";
export const metadata = {
    title: "Tourist Guide",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body suppressHydrationWarning={true}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
